# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
