# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(default='asd', max_length=120),
            preserve_default=False,
        ),
    ]
