# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_title_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='asd'),
            preserve_default=False,
        ),
    ]
