# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20161121_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateField(default='2016-05-17'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
