# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20161122_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 11, 22, 7, 16, 24, 972935)),
        ),
    ]
